sonar.projectKey=JakeRoxs_agendo_0e06f1d4-7d6a-4e3c-98e8-6e6e2bbcf351
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=**/*.test.ts
sonar.testExecutionReportPaths=reports/test-results.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info