/**
 * Command identifiers for the Agendo extension.
 *
 * Commands follow the format: "agendo.commandName".
 */
export enum Command {
  Refresh = "agendo.refresh",
  RefreshLoading = "agendo.refresh.loading",
  ShowDigest = "agendo.showDigest",
  ShowDigestLoading = "agendo.showDigest.loading",
  OpenBoard = "agendo.openBoard",
  OpenBoardLoading = "agendo.openBoard.loading",
  Filter = "agendo.filter",
  Search = "agendo.search",
  ClearSearch = "agendo.clearSearch",
  ClearFilters = "agendo.clearFilters",
  CreateTodo = "agendo.createTodo",
  CreateTodoLoading = "agendo.createTodo.loading",
  OpenPreview = "agendo.openPreview",
  SetViewMode = "agendo.setViewMode",
  SetStatusPending = "agendo.setStatus.pending",
  SetStatusReady = "agendo.setStatus.ready",
  SetStatusBacklogged = "agendo.setStatus.backlogged",
  SetStatusComplete = "agendo.setStatus.complete",
  SetStatusCancelled = "agendo.setStatus.cancelled",
  SetPriority = "agendo.setPriority",
  SetDependency = "agendo.setDependency",
  SetGroup = "agendo.setGroup",
  DeleteTodo = "agendo.deleteTodo",
  ChooseRoot = "agendo.chooseRoot",
  ToggleGitignore = "agendo.toggleGitignore",
  SetDefaultRoot = "agendo.setDefault.root",
  SetDefaultPriority = "agendo.setDefault.priority",
  SetDefaultPreview = "agendo.setDefault.preview",
  EnableSkill = "agendo.enableSkill",
  UpdateSkill = "agendo.updateSkill",
  EnableSkillLoading = "agendo.enableSkill.loading",
  UpdateSkillLoading = "agendo.updateSkill.loading",
  CollapseNode = "agendo.collapseNode",
  ExpandNode = "agendo.expandNode",
  ImportFromClipboard = "agendo.importFromClipboard",
  ImportFromClipboardLoading = "agendo.importFromClipboard.loading",
}
